# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            0x41.cf
tagline:          'InfoSec, Reversing, and more'
description:      'InfoSec, Reverse Engineering, and more (soon&trade;)'
url:              https://0x41.cf
#baseurl:          '/hydeout'

author:
  name:           'Sami ALAOUI KENDIL'
  url:            https://linkedin.com/thedroidgeek

github_username:      thedroidgeek
linkedin_username:    thedroidgeek

disqus:
  shortname:     0x41-cf

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
